version: '3,8'

services:
  db_api:
    image: postgres:15.0-alpine
    container_name: flat-rent
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"